export const BDP_SOURCE_METHOD = Object.freeze({
  API: 'api',
  GIS_SERVICE: 'gis-service',
  BULK_DOWNLOAD: 'bulk-download',
  LICENSED_FEED: 'licensed-feed',
  DOCUMENT_FEED: 'document-feed',
  PERMITTED_FETCH: 'permitted-fetch',
  MANUAL: 'manual',
});

export const BDP_AUTHORITY = Object.freeze({
  AUTHORITATIVE: 'authoritative',
  PRIMARY: 'primary',
  LICENSED: 'licensed',
  SECONDARY: 'secondary',
  ADVISORY: 'advisory',
});

export const BDP_REFRESH_CLASS = Object.freeze({
  LIVE: 'live',
  HOURLY: 'hourly',
  DAILY: 'daily',
  TWICE_WEEKLY: 'twice-weekly',
  WEEKLY: 'weekly',
  MONTHLY: 'monthly',
  QUARTERLY: 'quarterly',
  ANNUAL: 'annual',
  ON_DEMAND: 'on-demand',
});

/**
 * Initial BDP source policy. Cadences describe when BDP should check the
 * authoritative upstream source, not how often upstream itself changes.
 * Individual source adapters may override a cadence when the publisher exposes
 * a stronger update signal (ETag, Last-Modified, update timestamp, webhook,
 * ArcGIS edit metadata, etc.).
 */
export const BDP_DATA_SOURCES = Object.freeze({
  bexarParcels: Object.freeze({
    id: 'bexar-parcels',
    label: 'Bexar County Parcels / BCAD',
    method: BDP_SOURCE_METHOD.GIS_SERVICE,
    authority: BDP_AUTHORITY.PRIMARY,
    refreshClass: BDP_REFRESH_CLASS.ANNUAL,
    onDemandRefresh: true,
    cacheTtlMs: 24 * 60 * 60 * 1000,
    url: 'https://maps.bexar.org/arcgis/rest/services/Parcels/MapServer/0',
    notes: 'Official Bexar County ArcGIS parcel service sourced from BCAD; query by viewport or parcel id instead of crawling records.',
  }),
  travisParcels: Object.freeze({
    id: 'travis-parcels', label: 'Travis County Parcels / TCAD',
    method: BDP_SOURCE_METHOD.GIS_SERVICE, authority: BDP_AUTHORITY.PRIMARY,
    refreshClass: BDP_REFRESH_CLASS.ON_DEMAND, onDemandRefresh: true,
    cacheTtlMs: 24 * 60 * 60 * 1000,
    url: 'https://gis.traviscountytx.gov/server1/rest/services/Boundaries_and_Jurisdictions/TCAD_Travis_County_Property/MapServer/3',
    notes: 'County GIS layer with TCAD fields. Publication metadata for the separate TCAD_public service describes monthly assembly; this layer’s record currency, deed status and survey boundaries remain unverified.',
  }),
  williamsonParcels: Object.freeze({
    id: 'williamson-parcels', label: 'Williamson County Parcels / WCAD',
    method: BDP_SOURCE_METHOD.GIS_SERVICE, authority: BDP_AUTHORITY.PRIMARY,
    refreshClass: BDP_REFRESH_CLASS.ON_DEMAND, onDemandRefresh: true,
    cacheTtlMs: 24 * 60 * 60 * 1000,
    url: 'https://gis.wilco.org/arcgis/rest/services/public/county_wcad_parcels/MapServer/0',
    notes: 'Official county GIS WCAD parcel polygon layer. Service update information conflicts with an older description date; record currency and legal boundaries are unverified. Query bounded owner/property/viewport results.',
  }),
  texasRailroadCommission: Object.freeze({
    id: 'texas-rrc',
    label: 'Railroad Commission of Texas GIS',
    method: BDP_SOURCE_METHOD.BULK_DOWNLOAD,
    authority: BDP_AUTHORITY.PRIMARY,
    refreshClass: BDP_REFRESH_CLASS.TWICE_WEEKLY,
    onDemandRefresh: true,
    cacheTtlMs: 24 * 60 * 60 * 1000,
    url: 'https://www.rrc.texas.gov/resource-center/research/data-sets-available-for-download/',
    notes: 'RRC publishes county well and pipeline shapefile archives twice weekly. Prefer those official bulk products and targeted public GIS queries over automated crawling of the interactive viewer.',
  }),
  tceqWaterRights: Object.freeze({
    id: 'tceq-water-rights',
    label: 'TCEQ Surface Water Rights',
    method: BDP_SOURCE_METHOD.BULK_DOWNLOAD,
    authority: BDP_AUTHORITY.AUTHORITATIVE,
    refreshClass: BDP_REFRESH_CLASS.WEEKLY,
    onDemandRefresh: true,
    cacheTtlMs: 24 * 60 * 60 * 1000,
    url: 'https://www.tceq.texas.gov/permitting/water_rights/wr-permitting/wrwud',
    notes: 'Check TCEQ structured active/inactive water-right files for changes and use the official Water Rights Viewer for spatial verification/context rather than scraping the viewer UI.',
  }),
  tceqMunicipalSolidWaste: Object.freeze({
    id: 'tceq-msw',
    label: 'TCEQ Municipal Solid Waste Facilities',
    method: BDP_SOURCE_METHOD.BULK_DOWNLOAD,
    authority: BDP_AUTHORITY.AUTHORITATIVE,
    refreshClass: BDP_REFRESH_CLASS.WEEKLY,
    onDemandRefresh: true,
    cacheTtlMs: 24 * 60 * 60 * 1000,
    url: 'https://www.tceq.texas.gov/permitting/waste_permits/msw_permits/msw-data',
    notes: 'Use the official TCEQ weekly MSW facility spreadsheets for active/inactive/not-constructed, closed, revoked/not-issued, and historical unnumbered/unauthorized-site screening. Coordinates may represent a benchmark, gate, centroid, or other facility point, so point-on-parcel results remain screening evidence rather than proof of site boundaries or contamination.',
  }),
  epaCleanups: Object.freeze({
    id: 'epa-cleanups',
    label: 'EPA Cleanups in My Community',
    method: BDP_SOURCE_METHOD.GIS_SERVICE,
    authority: BDP_AUTHORITY.AUTHORITATIVE,
    refreshClass: BDP_REFRESH_CLASS.WEEKLY,
    onDemandRefresh: true,
    cacheTtlMs: 24 * 60 * 60 * 1000,
    url: 'https://services.arcgis.com/cJ9YHowT8TU7DUyn/arcgis/rest/services/Cleanups_in_my_Community_Sites/FeatureServer/0',
    notes: 'Use the modern EPA hosted feature layer for Superfund, RCRA corrective-action, Brownfields and response-site screening. Query by viewport/parcel vicinity; do not use the retired legacy CIMC MapServer.',
  }),
  txdotRoadways: Object.freeze({
    id: 'txdot-roadways',
    label: 'TxDOT Roadways / GRID',
    method: BDP_SOURCE_METHOD.GIS_SERVICE,
    authority: BDP_AUTHORITY.AUTHORITATIVE,
    refreshClass: BDP_REFRESH_CLASS.MONTHLY,
    onDemandRefresh: true,
    cacheTtlMs: 7 * 24 * 60 * 60 * 1000,
    url: 'https://services.arcgis.com/KTcxiTD9dsQw4r7Z/ArcGIS/rest/services/TxDOT_Roadways/FeatureServer/0',
    notes: 'Statewide TxDOT roadway network from GRID, including on-system and off-system public roads. Use for mapped road proximity/classification screening; mapped centerlines do not establish legal parcel access or frontage.',
  }),
  txdotAadt: Object.freeze({
    id: 'txdot-aadt',
    label: 'TxDOT Annual Average Daily Traffic',
    method: BDP_SOURCE_METHOD.GIS_SERVICE,
    authority: BDP_AUTHORITY.AUTHORITATIVE,
    refreshClass: BDP_REFRESH_CLASS.ANNUAL,
    onDemandRefresh: true,
    cacheTtlMs: 7 * 24 * 60 * 60 * 1000,
    url: 'https://services.arcgis.com/KTcxiTD9dsQw4r7Z/arcgis/rest/services/TxDOT_AADT/FeatureServer/0',
    notes: 'Current AADT stamped onto TxDOT roadway linework from GRID. Use as traffic-volume screening and preserve the published extract date.',
  }),
  txdotAadtHistory: Object.freeze({
    id: 'txdot-aadt-history',
    label: 'TxDOT Five-Year AADT Counts',
    method: BDP_SOURCE_METHOD.GIS_SERVICE,
    authority: BDP_AUTHORITY.AUTHORITATIVE,
    refreshClass: BDP_REFRESH_CLASS.ANNUAL,
    onDemandRefresh: true,
    cacheTtlMs: 7 * 24 * 60 * 60 * 1000,
    url: 'https://services.arcgis.com/KTcxiTD9dsQw4r7Z/ArcGIS/rest/services/TxDOT_5_Year_Statewide_AADT_Traffic_Counts/FeatureServer/0',
    notes: 'Five-year statewide TxDOT count-station history. Keep station trend separate from the nearest roadway segment unless the station/route relationship is explicitly verified.',
  }),
  twdbWaterServiceAreas: Object.freeze({
    id: 'twdb-water-service-areas',
    label: 'TWDB Current Public Water Service Areas',
    method: BDP_SOURCE_METHOD.GIS_SERVICE,
    authority: BDP_AUTHORITY.PRIMARY,
    refreshClass: BDP_REFRESH_CLASS.MONTHLY,
    onDemandRefresh: true,
    cacheTtlMs: 7 * 24 * 60 * 60 * 1000,
    url: 'https://services.twdb.texas.gov/arcgis/rest/services/PWS/Public_Water_Service_Areas/MapServer/0',
    notes: 'Self-reported current retail water-service boundaries are screening evidence for who currently serves an area. They are not the same as CCN territory and do not establish capacity, tap availability, extension cost or will-serve commitment.',
  }),
  puctWaterCcn: Object.freeze({
    id: 'puct-water-ccn',
    label: 'PUCT Water CCN Territory',
    method: BDP_SOURCE_METHOD.GIS_SERVICE,
    authority: BDP_AUTHORITY.PRIMARY,
    refreshClass: BDP_REFRESH_CLASS.QUARTERLY,
    onDemandRefresh: true,
    cacheTtlMs: 30 * 24 * 60 * 60 * 1000,
    url: 'https://services.twdb.texas.gov/arcgis/rest/services/PWS/Public_Utility_Commission_CCN_Water/MapServer/0',
    notes: 'Water CCN polygons represent legal service territory, not proof of current capacity or a development-specific service commitment. The TWDB-hosted GIS copy may lag current PUCT filings, so acquisition decisions require current PUCT/provider verification.',
  }),
  usGovernmentTransmissionArchive: Object.freeze({
    id: 'us-government-transmission-archive',
    label: 'U.S. Government Transmission Infrastructure Archive',
    method: BDP_SOURCE_METHOD.GIS_SERVICE,
    authority: BDP_AUTHORITY.ADVISORY,
    refreshClass: BDP_REFRESH_CLASS.ON_DEMAND,
    onDemandRefresh: false,
    cacheTtlMs: 30 * 24 * 60 * 60 * 1000,
    url: 'https://services.arcgis.com/707Mk8fFdkSwTkI9/ArcGIS/rest/services/PowerTransmissionInfrastructure_ExportFeatures/FeatureServer/0',
    notes: 'Archived public U.S. Government high-voltage transmission screening layer, last maintained in 2024. Do not present it as current electric service, distribution capacity, easement proof or exact surveyed line location.',
  }),
  usdaSsurgO: Object.freeze({
    id: 'usda-ssurgo',
    label: 'USDA NRCS SSURGO',
    method: BDP_SOURCE_METHOD.BULK_DOWNLOAD,
    authority: BDP_AUTHORITY.AUTHORITATIVE,
    refreshClass: BDP_REFRESH_CLASS.ANNUAL,
    onDemandRefresh: false,
    cacheTtlMs: 30 * 24 * 60 * 60 * 1000,
    notes: 'Maintain a local Texas spatial copy and replace it on the official annual refresh.',
  }),
  thcHistoricSitesAtlas: Object.freeze({
    id: 'thc-historic-sites-atlas',
    label: 'Texas Historical Commission Historic Sites Atlas',
    method: BDP_SOURCE_METHOD.GIS_SERVICE,
    authority: BDP_AUTHORITY.AUTHORITATIVE,
    refreshClass: BDP_REFRESH_CLASS.MONTHLY,
    onDemandRefresh: true,
    cacheTtlMs: 7 * 24 * 60 * 60 * 1000,
    url: 'https://services7.arcgis.com/2hv9bZMrcgZpr7i9/ArcGIS/rest/services/Historical/FeatureServer',
    notes: 'Use the public THC Atlas cemetery and public historic-designation layers for screening. Exact archeological site locations are restricted cultural-resource information and must never be exposed or treated as cleared by absence from the public Atlas.',
  }),
  sanAntonioZoning: Object.freeze({
    id: 'san-antonio-zoning',
    label: 'City of San Antonio Zoning',
    method: BDP_SOURCE_METHOD.GIS_SERVICE,
    authority: BDP_AUTHORITY.AUTHORITATIVE,
    refreshClass: BDP_REFRESH_CLASS.WEEKLY,
    onDemandRefresh: true,
    cacheTtlMs: 24 * 60 * 60 * 1000,
    url: 'https://services.arcgis.com/g1fRTDLeMgspWrYp/arcgis/rest/services/COSA_Zoning/FeatureServer/12',
    notes: 'Official City zoning GIS used for preliminary jurisdiction/base-zoning screening. GIS does not establish vested rights, legally permitted development, overlays, variances, plat status or current case/ordinance interpretation.',
  }),
  sanAntonioEtj: Object.freeze({
    id: 'san-antonio-etj',
    label: 'City of San Antonio ETJ',
    method: BDP_SOURCE_METHOD.GIS_SERVICE,
    authority: BDP_AUTHORITY.AUTHORITATIVE,
    refreshClass: BDP_REFRESH_CLASS.QUARTERLY,
    onDemandRefresh: true,
    cacheTtlMs: 7 * 24 * 60 * 60 * 1000,
    url: 'https://services.arcgis.com/g1fRTDLeMgspWrYp/arcgis/rest/services/COSA_ETJ/FeatureServer/3',
    notes: 'Official ETJ geometry for jurisdiction screening. ETJ presence does not imply City base zoning and requires separate county/City subdivision and development-control review.',
  }),
  sanAntonioFutureLandUse: Object.freeze({
    id: 'san-antonio-future-land-use',
    label: 'City of San Antonio Future Land Use',
    method: BDP_SOURCE_METHOD.GIS_SERVICE,
    authority: BDP_AUTHORITY.AUTHORITATIVE,
    refreshClass: BDP_REFRESH_CLASS.QUARTERLY,
    onDemandRefresh: true,
    cacheTtlMs: 7 * 24 * 60 * 60 * 1000,
    url: 'https://services.arcgis.com/g1fRTDLeMgspWrYp/arcgis/rest/services/Future_Land_Use/FeatureServer/4',
    notes: 'Adopted future-land-use planning polygons support broad consistency screening only; they are not zoning and do not guarantee rezoning, density or entitlement.',
  }),
  localOrdinances: Object.freeze({
    id: 'local-ordinances',
    label: 'Local ordinances / comprehensive plans',
    method: BDP_SOURCE_METHOD.DOCUMENT_FEED,
    authority: BDP_AUTHORITY.AUTHORITATIVE,
    refreshClass: BDP_REFRESH_CLASS.WEEKLY,
    onDemandRefresh: true,
    cacheTtlMs: 24 * 60 * 60 * 1000,
    notes: 'Use municipal code feeds, published agendas, plan repositories, and change checks; permitted page retrieval is a fallback only.',
  }),
});

export function getBdpSourcePolicy(id) {
  return Object.values(BDP_DATA_SOURCES).find((source) => source.id === id) || null;
}
