import {
  buildRrcCountyArchiveName,
  getRrcCountyDataset,
  normalizeTexasCountyFips,
} from './rrcCatalog.js';

export const RRC_MFT_FOLDER_URLS = Object.freeze({
  pipelines: 'https://mft.rrc.texas.gov/link/c7cbab0c-afe2-4f6f-91ae-e6ed7d3a7ab6',
  wells: 'https://mft.rrc.texas.gov/link/d551fb20-442e-4b67-84fa-ac3f23ecabb4',
});

function stripHtml(value) {
  return String(value || '')
    .replace(/<[^>]*>/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/\s+/g, ' ')
    .trim();
}

function unescapeHtmlAttribute(value) {
  return String(value || '')
    .replace(/&amp;/g, '&')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'");
}

export function getRrcMftFolderUrl(dataset) {
  getRrcCountyDataset(dataset);
  const key = String(dataset).trim().toLowerCase();
  const url = RRC_MFT_FOLDER_URLS[key];
  if (!url) throw new Error(`No RRC download folder configured for ${dataset}`);
  return url;
}

/**
 * Resolve an archive URL from RRC's public GoAnywhere HTTPS folder page.
 *
 * The folder URL is the stable publisher-owned reference. The individual file
 * link generated by GoAnywhere may change, so BDP discovers it from the
 * current official listing rather than persisting a short-lived download URL.
 */
export function extractRrcArchiveHref(html, filename, folderUrl) {
  const expected = String(filename || '').trim();
  if (!expected) throw new Error('RRC archive filename is required');

  const anchors = String(html || '').matchAll(
    /<a\b[^>]*?href\s*=\s*(["'])(.*?)\1[^>]*>([\s\S]*?)<\/a>/gi,
  );

  for (const match of anchors) {
    const href = unescapeHtmlAttribute(match[2]);
    const text = stripHtml(match[3]);
    if (text === expected || href.includes(expected) || href.includes(encodeURIComponent(expected))) {
      return new URL(href, folderUrl).href;
    }
  }

  // Some GoAnywhere skins place a generated file URL in a data attribute or
  // inline script instead of the anchor href. Keep this fallback deliberately
  // narrow: only accept an HTTP(S) URL that explicitly contains our filename.
  const urlMatches = String(html || '').matchAll(/https?:\\?\/\\?\/[^\s"'<>]+/gi);
  for (const match of urlMatches) {
    const candidate = match[0].replace(/\\\//g, '/').replace(/&amp;/g, '&');
    if (candidate.includes(expected) || candidate.includes(encodeURIComponent(expected))) {
      return candidate;
    }
  }

  return null;
}

export async function resolveRrcCountyArchive({
  dataset,
  countyFips,
  fetchImpl = globalThis.fetch,
} = {}) {
  if (typeof fetchImpl !== 'function') throw new Error('A fetch implementation is required');

  const countyCode = normalizeTexasCountyFips(countyFips);
  const filename = buildRrcCountyArchiveName(dataset, countyCode);
  const folderUrl = getRrcMftFolderUrl(dataset);
  const response = await fetchImpl(folderUrl, {
    headers: {
      accept: 'text/html,application/xhtml+xml',
      'user-agent': 'BDP-Land-Intelligence/0.1 (+official-public-data-ingestion)',
    },
  });

  if (!response.ok) {
    throw new Error(`RRC folder request failed (${response.status}) for ${dataset}`);
  }

  const html = await response.text();
  const downloadUrl = extractRrcArchiveHref(html, filename, folderUrl);
  if (!downloadUrl) {
    throw new Error(`RRC archive ${filename} was not found in the current official folder listing`);
  }

  return Object.freeze({
    dataset: String(dataset).trim().toLowerCase(),
    countyFips: countyCode,
    filename,
    folderUrl,
    downloadUrl,
  });
}

export async function sha256Hex(bytes) {
  const input = bytes instanceof ArrayBuffer
    ? bytes
    : ArrayBuffer.isView(bytes)
      ? bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength)
      : null;
  if (!input) throw new TypeError('sha256Hex expects an ArrayBuffer or typed array');

  const digest = await globalThis.crypto.subtle.digest('SHA-256', input);
  return Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, '0')).join('');
}
